# Generated by Django 6.0.5 on 2026-05-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='countrystat',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='analytics.analytics'),
        ),
        migrations.AddField(
            model_name='devicestat',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='analytics.analytics'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='analytics.analytics'),
        ),
        migrations.AddField(
            model_name='viewstat',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='analytics.analytics'),
        ),
        migrations.AddField(
            model_name='visitorstat',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='analytics.analytics'),
        ),
    ]
