# Generated by Django 6.0.5 on 2026-05-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('portfolios', '0008_blog_dateraw_blog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('click_count', models.IntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_clicks', to='portfolios.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='portfolios.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='portfolios.project')),
            ],
        ),
    ]
