# Generated by Django 6.0.5 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_projectclick_projectclicklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclicklog',
            name='click_type',
            field=models.CharField(choices=[('github', 'GitHub'), ('live_demo', 'Live Demo')], default='github', max_length=20),
        ),
    ]
