# Generated by Django 6.0.5 on 2026-05-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_projectclicklog_click_type'),
        ('portfolios', '0008_blog_dateraw_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclick',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectclick',
            name='portfolio_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectclick',
            name='portfolio_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectclick',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectclicklog',
            name='click_type',
            field=models.CharField(choices=[('github', 'GitHub'), ('live_demo', 'Live Demo'), ('title', 'Project Title')], default='github', max_length=20),
        ),
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.CharField(default='', max_length=64)),
                ('viewer_session', models.CharField(blank=True, default='', max_length=128)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('is_owner_view', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_views', to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'viewed_at'], name='analytics_p_portfol_d19ade_idx'), models.Index(fields=['portfolio', 'viewer_ip', 'viewed_at'], name='analytics_p_portfol_11e2e0_idx')],
            },
        ),
    ]
