# Generated by Django 6.0.5 on 2026-05-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_projectclick_is_popular_projectclick_portfolio_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portfolioview',
            name='analytics_p_portfol_d19ade_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolioview',
            name='analytics_p_portfol_11e2e0_idx',
        ),
        migrations.RemoveField(
            model_name='projectclicklog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='portfolioview',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='ProjectClick',
        ),
        migrations.DeleteModel(
            name='ProjectClickLog',
        ),
        migrations.DeleteModel(
            name='PortfolioView',
        ),
    ]
