# Generated by Django 6.0.5 on 2026-06-01 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_portfolioview_analytics_p_portfol_d19ade_idx_and_more'),
        ('portfolios', '0014_portfolio_custom_og_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('discord', 'Discord'), ('direct', 'Direct Link'), ('other', 'Other')], default='other', max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'clicked_at'], name='analytics_s_portfol_f9d51f_idx'), models.Index(fields=['platform'], name='analytics_s_platfor_c581ea_idx')],
            },
        ),
    ]
