# Generated by Django 6.0.5 on 2026-06-01 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_socialshareevent'),
        ('portfolios', '0014_portfolio_custom_og_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSCConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('property_url', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_connection', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='SitemapSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_engine', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_submissions', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='BacklinkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('referring_domains', models.IntegerField(default=0)),
                ('backlinks_count', models.IntegerField(default=0)),
                ('new_backlinks', models.IntegerField(default=0)),
                ('lost_backlinks', models.IntegerField(default=0)),
                ('domain_authority', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_metrics', to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'date'], name='analytics_b_portfol_235e55_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('seo_score', models.IntegerField(default=0)),
                ('backlinks_count', models.IntegerField(default=0)),
                ('visibility_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('lcp', models.FloatField(default=0.0)),
                ('cls', models.FloatField(default=0.0)),
                ('inp', models.IntegerField(default=0)),
                ('ttfb', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=100)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'date'], name='analytics_p_portfol_a225de_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SEOAuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_score', models.IntegerField()),
                ('details', models.JSONField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'created_at'], name='analytics_s_portfol_5725d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordRankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('best_rank', models.IntegerField(blank=True, null=True)),
                ('worst_rank', models.IntegerField(blank=True, null=True)),
                ('search_engine', models.CharField(default='google', max_length=50)),
                ('tracked_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='analytics.trackedkeyword')),
            ],
            options={
                'indexes': [models.Index(fields=['tracked_keyword', 'date'], name='analytics_k_tracked_3ae6dd_idx')],
                'unique_together': {('tracked_keyword', 'date', 'search_engine')},
            },
        ),
    ]
