# Generated by Django 6.0.5 on 2026-06-01 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_gscconnection_sitemapsubmission_trackedkeyword_and_more'),
        ('portfolios', '0014_portfolio_custom_og_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lcp', models.FloatField(default=0.0)),
                ('cls', models.FloatField(default=0.0)),
                ('inp', models.IntegerField(default=0)),
                ('fcp', models.FloatField(default=0.0)),
                ('ttfb', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'timestamp'], name='analytics_p_portfol_d32c7d_idx')],
            },
        ),
    ]
