# Generated by Django 6.0.5 on 2026-06-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_performancemetriclog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backlinkmetric',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='backlinkmetric',
            name='analytics_b_portfol_235e55_idx',
        ),
        migrations.AlterUniqueTogether(
            name='competitorbenchmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='competitorbenchmark',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='gscconnection',
            name='portfolio',
        ),
        migrations.AlterUniqueTogether(
            name='keywordrankinghistory',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='keywordrankinghistory',
            name='analytics_k_tracked_3ae6dd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='performancemetric',
            name='analytics_p_portfol_a225de_idx',
        ),
        migrations.RemoveIndex(
            model_name='performancemetriclog',
            name='analytics_p_portfol_d32c7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='seoaudithistory',
            name='analytics_s_portfol_5725d4_idx',
        ),
        migrations.RemoveField(
            model_name='sitemapsubmission',
            name='portfolio',
        ),
        migrations.AlterUniqueTogether(
            name='trackedkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trackedkeyword',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='backlinkmetric',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='CompetitorBenchmark',
        ),
        migrations.DeleteModel(
            name='GSCConnection',
        ),
        migrations.RemoveField(
            model_name='keywordrankinghistory',
            name='tracked_keyword',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='performancemetriclog',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='seoaudithistory',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='SitemapSubmission',
        ),
        migrations.DeleteModel(
            name='BacklinkMetric',
        ),
        migrations.DeleteModel(
            name='KeywordRankingHistory',
        ),
        migrations.DeleteModel(
            name='TrackedKeyword',
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.DeleteModel(
            name='PerformanceMetricLog',
        ),
        migrations.DeleteModel(
            name='SEOAuditHistory',
        ),
    ]
