# Generated by Django 6.0.5 on 2026-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_backlinkmetric_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialshareevent',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='first_touch_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='first_touch_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='first_touch_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='last_touch_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='last_touch_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='last_touch_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='source',
            field=models.CharField(default='Direct', max_length=100),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialshareevent',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
