# Generated by Django 6.0.5 on 2026-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_facebook_profile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
