# Generated by Django 6.0.5 on 2026-05-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_edited_portfolio_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
