# Generated by Django 6.0.5 on 2026-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
