# Generated by Django 6.0.5 on 2026-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_project_github_alter_project_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='awards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='music',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='volunteer',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
