# Generated by Django 6.0.5 on 2026-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_portfolio_user_portfolioevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioevent',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='device',
            field=models.CharField(default='Desktop', max_length=50),
        ),
    ]
