# Generated by Django 6.0.5 on 2026-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_portfolioevent_country_portfolioevent_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
