# Generated by Django 6.0.5 on 2026-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_portfolio_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dateRaw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
