# Generated by Django 6.0.5 on 2026-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_blog_dateraw_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
