# Generated by Django 6.0.5 on 2026-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_portfolio_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
