# Generated by Django 6.0.5 on 2026-05-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(default='anonymous', max_length=255)),
                ('link_type', models.CharField(default='live', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='portfolios.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'visitor_id', 'created_at'], name='portfolios__project_ab49bb_idx')],
            },
        ),
    ]
