# Generated by Django 6.0.5 on 2026-05-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_add_project_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=10)),
                ('visit_count', models.IntegerField(default=1)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_visits', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'country_name', 'country_code')},
            },
        ),
    ]
