# Generated by Django 6.0.5 on 2026-05-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_add_portfolio_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('visit_count', models.IntegerField(default=1)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'source')},
            },
        ),
    ]
