# Generated by Django 6.0.5 on 2026-06-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_trafficsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='custom_og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom_seo_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom_seo_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
