# Generated by Django 6.0.5 on 2026-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_portfolio_profile_bio_portfolio_profile_calendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioevent',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='source',
            field=models.CharField(default='Direct', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioevent',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
