# Generated by Django 6.0.5 on 2026-06-09 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_portfoliomessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='portfoliomessage',
            name='portfolios__portfol_7a2420_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='portfoliomessage',
            name='portfolio',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'created_at'], name='portfolios__user_id_58dd33_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='portfolios__user_id_235b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'portfolio', 'created_at'], name='portfolios__user_id_708687_idx'),
        ),
        migrations.DeleteModel(
            name='PortfolioMessage',
        ),
    ]
