# Generated by Django 6.0.5 on 2026-06-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['portfolio', 'event_type', 'created_at'], name='portfolios__portfol_0944c6_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['portfolio', 'created_at'], name='portfolios__portfol_1d9a3b_idx'),
        ),
    ]
