export const defaultPortfolio = {
  user: {
    name: "",
    username: "",
    title: "",
    location: "",
    email: "",
    phone: "",
    avatar: "",
    bio: "",
    social: {
      github: "",
      twitter: "",
      linkedin: "",
      website: "",
    },
    resume_link: "",
  },
  sections: ["About", "Skills", "Experience", "Education", "Projects", "Testimonials", "Contact"],
  skills: [],
  experience: [],
  education: [],
  projects: [],
  certifications: [],
  testimonials: [],
  blogs: [],
  services: [],
  languages: [],
  volunteer: [],
  awards: [],
  references: [],
  faqs: [],
  contact: { email: "", calendly: "" },
  custom: {},
};

export const mockPortfolios = [
  { id: "1", name: "Personal Portfolio", template: "Developer", views: 12483, status: "Published", updated: "2h ago" },
  { id: "2", name: "Freelance Site", template: "Creative", views: 4218, status: "Draft", updated: "Yesterday" },
  { id: "3", name: "Resume Page", template: "Minimal", views: 891, status: "Published", updated: "3d ago" },
];
