export const templates = [
  // ─── Original 6 ────────────────────────────────────────────────────────────
  {
    id: "minimal",
    name: "Minimal Clean",
    tag: "Minimal",
    category: "Minimal",
    price: "Free",
    color: "from-slate-400 to-slate-600",
    accent: "#64748b",
    desc: "Editorial silence. Pure whitespace. Lets the work breathe.",
    preview: { lines: [3, 8, 5, 6], dots: "slate" },
  },
  {
    id: "creative",
    name: "Creative Dark",
    tag: "Creative",
    category: "Creative",
    price: "Free",
    color: "from-pink-500 to-orange-500",
    accent: "#f97316",
    desc: "Big type, generous whitespace, gallery-led layouts.",
    preview: { lines: [6, 4, 7, 3], dots: "orange" },
  },
  {
    id: "gradient",
    name: "Modern Gradient",
    tag: "Premium",
    category: "Developer",
    price: "Free",
    color: "from-violet-500 to-sky-500",
    accent: "#7c3aed",
    desc: "Frosted glass layers, depth, soft ambient glow.",
    preview: { lines: [5, 7, 4, 6], dots: "violet" },
  },
  {
    id: "classic",
    name: "Classic Professional",
    tag: "Business",
    category: "Business",
    price: "Free",
    color: "from-emerald-500 to-teal-500",
    accent: "#10b981",
    desc: "KPIs, traction, a clean story-driven layout.",
    preview: { lines: [4, 6, 5, 7], dots: "emerald" },
  },
  {
    id: "bold",
    name: "Bold Typography",
    tag: "Creative",
    category: "Creative",
    price: "Free",
    color: "from-fuchsia-500 to-cyan-500",
    accent: "#d946ef",
    desc: "Glitch motion, neon grid, retro CRT vibes.",
    preview: { lines: [7, 3, 8, 4], dots: "fuchsia" },
  },
  {
    id: "developer",
    name: "Developer / Tech",
    tag: "Code-first",
    category: "Developer",
    price: "Free",
    color: "from-indigo-500 to-blue-500",
    accent: "#6366f1",
    desc: "Mono fonts, terminal vibes, GitHub-native.",
    preview: { lines: [5, 8, 3, 6], dots: "indigo" },
  },

  // ─── 20 New Templates ───────────────────────────────────────────────────────
  {
    id: "aurora",
    name: "Aurora Borealis",
    tag: "Dreamy",
    category: "Creative",
    price: "Free",
    color: "from-green-400 via-teal-400 to-blue-500",
    accent: "#2dd4bf",
    desc: "Sweeping aurora gradients meet frosted glass cards.",
    preview: { lines: [6, 5, 8, 4], dots: "teal" },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk 2099",
    tag: "Neon",
    category: "Creative",
    price: "Free",
    color: "from-yellow-400 to-pink-600",
    accent: "#facc15",
    desc: "Yellow & magenta neon on a dark dystopian grid.",
    preview: { lines: [7, 4, 6, 5], dots: "yellow" },
  },
  {
    id: "obsidian",
    name: "Obsidian Executive",
    tag: "Luxury",
    category: "Business",
    price: "Free",
    color: "from-zinc-700 to-zinc-900",
    accent: "#a1a1aa",
    desc: "Black stone, silver accents — boardroom-ready.",
    preview: { lines: [4, 7, 5, 6], dots: "zinc" },
  },
  {
    id: "sakura",
    name: "Sakura Blossom",
    tag: "Elegant",
    category: "Creative",
    price: "Free",
    color: "from-rose-300 to-pink-500",
    accent: "#fb7185",
    desc: "Soft pinks & petals. Delicate and memorable.",
    preview: { lines: [5, 6, 4, 7], dots: "rose" },
  },
  {
    id: "terminal",
    name: "Hacker Terminal",
    tag: "Code-first",
    category: "Developer",
    price: "Free",
    color: "from-green-600 to-green-900",
    accent: "#22c55e",
    desc: "Green-on-black matrix terminal. Pure hacker aesthetic.",
    preview: { lines: [8, 3, 7, 4], dots: "green" },
  },
  {
    id: "oceanic",
    name: "Deep Oceanic",
    tag: "Serene",
    category: "Creative",
    price: "Free",
    color: "from-blue-700 via-cyan-600 to-teal-500",
    accent: "#06b6d4",
    desc: "Submerged depths, bioluminescent highlights.",
    preview: { lines: [5, 7, 6, 4], dots: "cyan" },
  },
  {
    id: "paper",
    name: "Paper & Ink",
    tag: "Print",
    category: "Minimal",
    price: "Free",
    color: "from-amber-100 to-stone-300",
    accent: "#78716c",
    desc: "Newspaper typography, serif fonts, ink-on-paper feel.",
    preview: { lines: [4, 6, 5, 7], dots: "stone" },
  },
  {
    id: "space",
    name: "Space Explorer",
    tag: "Cosmic",
    category: "Creative",
    price: "Free",
    color: "from-slate-900 via-purple-900 to-indigo-900",
    accent: "#818cf8",
    desc: "Starfields, cosmic purple glows, planetary depth.",
    preview: { lines: [6, 5, 7, 3], dots: "indigo" },
  },
  {
    id: "retro",
    name: "Retro Wave",
    tag: "80s",
    category: "Creative",
    price: "Free",
    color: "from-purple-800 via-pink-700 to-orange-500",
    accent: "#ec4899",
    desc: "Synthwave grid, chrome text, retro sunset palette.",
    preview: { lines: [7, 4, 5, 6], dots: "pink" },
  },
  {
    id: "scandinavian",
    name: "Scandinavian",
    tag: "Nordic",
    category: "Minimal",
    price: "Free",
    color: "from-sky-100 to-blue-200",
    accent: "#0284c7",
    desc: "Hygge aesthetics — clean, warm, and understated.",
    preview: { lines: [4, 5, 6, 3], dots: "sky" },
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism Pro",
    tag: "Glass",
    category: "Developer",
    price: "Free",
    color: "from-white/20 via-purple-400/30 to-blue-500/40",
    accent: "#a78bfa",
    desc: "Layered frosted glass, blur depth, translucent cards.",
    preview: { lines: [6, 7, 4, 5], dots: "violet" },
  },
  {
    id: "brutalist",
    name: "Brutalist Web",
    tag: "Raw",
    category: "Creative",
    price: "Free",
    color: "from-yellow-300 to-black",
    accent: "#fbbf24",
    desc: "Bold borders, raw type, unapologetically loud.",
    preview: { lines: [8, 5, 3, 7], dots: "yellow" },
  },
  {
    id: "coral",
    name: "Coral Reef",
    tag: "Vibrant",
    category: "Creative",
    price: "Free",
    color: "from-orange-400 to-red-500",
    accent: "#f97316",
    desc: "Warm coral tones with bright aquatic energy.",
    preview: { lines: [5, 6, 7, 4], dots: "orange" },
  },
  {
    id: "monochrome",
    name: "Monochrome Studio",
    tag: "Gallery",
    category: "Minimal",
    price: "Free",
    color: "from-gray-100 to-gray-400",
    accent: "#374151",
    desc: "Black & white gallery focus — art director's choice.",
    preview: { lines: [4, 7, 5, 6], dots: "gray" },
  },
  {
    id: "startup",
    name: "Startup Pitch",
    tag: "Growth",
    category: "Business",
    price: "Free",
    color: "from-blue-500 to-indigo-600",
    accent: "#3b82f6",
    desc: "Metric-driven, investor-ready, traction-first.",
    preview: { lines: [6, 4, 7, 5], dots: "blue" },
  },
  {
    id: "forest",
    name: "Forest & Earth",
    tag: "Nature",
    category: "Minimal",
    price: "Free",
    color: "from-lime-600 to-emerald-800",
    accent: "#84cc16",
    desc: "Earthy greens, organic textures, grounded energy.",
    preview: { lines: [5, 7, 4, 6], dots: "lime" },
  },
  {
    id: "dusk",
    name: "Golden Dusk",
    tag: "Warm",
    category: "Creative",
    price: "Free",
    color: "from-amber-500 via-orange-500 to-rose-600",
    accent: "#f59e0b",
    desc: "Hour-glass warmth — sunset amber, rose horizon.",
    preview: { lines: [6, 5, 7, 4], dots: "amber" },
  },
  {
    id: "neon",
    name: "Neon Noir",
    tag: "Dark",
    category: "Creative",
    price: "Free",
    color: "from-gray-900 via-cyan-900 to-purple-900",
    accent: "#22d3ee",
    desc: "Electric cyan on black, rain-soaked city nights.",
    preview: { lines: [7, 3, 6, 5], dots: "cyan" },
  },
  {
    id: "architect",
    name: "Architect Grid",
    tag: "Structured",
    category: "Business",
    price: "Free",
    color: "from-slate-300 to-blue-400",
    accent: "#60a5fa",
    desc: "Blueprint grids, precise columns, structured clarity.",
    preview: { lines: [4, 6, 5, 7], dots: "blue" },
  },
  {
    id: "holographic",
    name: "Holographic",
    tag: "Futuristic",
    category: "Developer",
    price: "Free",
    color: "from-cyan-400 via-pink-400 to-yellow-400",
    accent: "#f472b6",
    desc: "Iridescent rainbow shimmer, holographic foil effect.",
    preview: { lines: [7, 5, 6, 4], dots: "pink" },
  },
  {
    id: "typewriter",
    name: "Typewriter",
    tag: "Vintage",
    category: "Minimal",
    price: "Free",
    color: "from-stone-500 to-stone-700",
    accent: "#a8a29e",
    desc: "Vintage ribbon feel, aged paper, typeface nostalgia.",
    preview: { lines: [5, 4, 6, 7], dots: "stone" },
  },
  {
    id: "quantum",
    name: "Quantum Dark",
    tag: "Sci-Fi",
    category: "Developer",
    price: "Free",
    color: "from-violet-900 via-blue-900 to-teal-800",
    accent: "#818cf8",
    desc: "Particle grids, quantum teal glows, sci-fi precision.",
    preview: { lines: [6, 7, 5, 4], dots: "violet" },
  },
];

export const templateCategories = ["All", "Developer", "Creative", "Minimal", "Business"];

export const themes = [
  { id: "minimal", name: "Minimal", swatch: ["#fafafa", "#111111"] },
  { id: "midnight", name: "Midnight", swatch: ["#0b0f1a", "#7c3aed"] },
  { id: "forest", name: "Forest", swatch: ["#0f1f15", "#22c55e"] },
  { id: "sand", name: "Sand", swatch: ["#f5f0e6", "#a16207"] },
  { id: "slate", name: "Slate", swatch: ["#1e293b", "#94a3b8"] },
  { id: "noir", name: "Noir", swatch: ["#000000", "#e5e7eb"] },
  { id: "twilight", name: "Twilight", swatch: ["#1e1b4b", "#f472b6"] },
  { id: "gradientblue", name: "Gradient Blue", swatch: ["#0ea5e9", "#6366f1"] },
  { id: "glass", name: "Glass Finish", swatch: ["#cbd5e1", "#a78bfa"] },
  { id: "neon", name: "Vibrant Neon", swatch: ["#0a0a0a", "#22d3ee"] },
];
